<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'MBtecZfFullUrl\Module'                         => __DIR__ . '/Module.php',
    'MBtecZfFullUrl\Mvc\Controller\Plugin\FullUrl'  => __DIR__ . '/src/FullUrl/Mvc/Controller/Plugin/FullUrl.php',
];
